export const menuList = [
  "Paneer Tikka Masala",
  "Butter Chicken",
  "Chana Masala",
  "Dal Makhani",
  "Vegetable Biryani",
  "Rajma",
  "Omelette",
  "Aloo Paratha",
  "Chicken Curry",
  "Naan",
  "Palak Paneer",
  "Margherita Pizza",
  "Spaghetti Carbonara",
  "Lasagna",
  "Garlic Bread",
  "Egg Sandwich",
  "Pancakes",
  "French Toast",
  "Omelette",
  "Masala Dosa",
  "Idli Sambhar",
  "Tandoori Chicken",
  "Veg Pulao",
  "Mutton Rogan Josh",
  "Pasta Alfredo",
  "Cesar Salad",
  "Chicken Wings",
  "Vegetable Manchurian",
  "Sushi Rolls",
  "Fried Rice",
];
